name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.3.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/

# flutter_intl:
#   enabled: true
#   arb_dir: lib/l10n
#   output_dir: lib/l10n

# arb-dir: lib/l10n
# template-arb-file: app_en.arb
# output-localization-file: app_localizations.dart

# flutter_intl:
#   enabled: true
#   arb_dir: /lib/app_localization/l10n